# Dev 환경 설정
spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
    enabled-by-default: 'false'

endpoint:
  health:
    enabled: 'true'
    show-details: always

---

# Local 환경 설정
spring:
  profiles:
    active: local
    default: local  # default 프로필을 local로 설정

management:
  endpoints:
    web:
      exposure:
        include: health
    enabled-by-default: 'false'

endpoint:
  health:
    enabled: 'true'
    show-details: always

---

# Prod 환경 설정
spring:
  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: health
    enabled-by-default: 'false'

endpoint:
  health:
    enabled: 'true'
    show-details: always

---

#데이터베이스 환경설정
spring:
  datasource:
    url: jdbc:mysql://localhost:3305/mysql
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver